name: Android Emulator

on: [push, pull_request]

jobs:
  test:
      runs-on: macos-10.15
      continue-on-error: true
      steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          # the `googleapis` emulator target considerably slower on CI.
          target: default
          profile: Nexus 5X
          script: sh ./.github/workflows/android_test.sh
      - uses: actions/upload-artifact@master
        if: ${{ always() }}
        with:
          name: log
          path: |
            ~/logcat.log
